### ISSUE TITLE
view in nagios UI

### ISSUE THREAD

**Issue by sushantp** [mzupan/nagios-plugin-mongodb#142]
Please help me to understand the following:
1. Can I view the mongodb statistics on Nagios UI(front-end). I am able to run in command line but donot see the statistics in nagios UI.
2. Can the plugin generate mail whenever the server gets down.

Please help me. I am using centos.

**Comment by mzupan** [comment]
this really isn't a plugin issue.. your issue is you need to learn how to do that in nagios itself.

**Comment by sushantp** [comment]
Hi Mike,
Thanks for your reply. From your reply I understand that the plugin is
capable of transferring the mongodb statistics to nagios UI. Kindly confirm.

On Mon, Jan 12, 2015 at 10:03 PM, Mike Zupan <notifications@github.com>
wrote:

> Closed #142 <https://github.com/mzupan/nagios-plugin-mongodb/issues/142>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mzupan/nagios-plugin-mongodb/issues/142#event-217487180>
> .
>



-- 
Warm regards,

Sushant Kumar Prusty
Cell: +91 9911888421
Skype: sushant.p

**Comment by mzupan** [comment]
yes it is.. you add the -D flag

https://github.com/mzupan/nagios-plugin-mongodb/blob/master/check_mongodb.py#L140
