### ISSUE TITLE
nagios-plugin-mongodb

### ISSUE THREAD

**Issue by trimurthyp** [mzupan/nagios-plugin-mongodb#143]
Hi 
This plugin is not working if authentication is enabled, and I am not able to find out how to use this plugin if authentication is enabled.

Can you please help me out how to do this, is there any other alternatives are available for this.

thank you.

**Comment by trimurthyp** [comment]
Hi All,
Please ignore this comment, I got to know how to use the plugin now.
it was my misunderstanding about the usage of the plugin.
Thank you.

**Comment by thias** [comment]
Since there is no probem, could you please close this issue?
