### ISSUE TITLE
Connect to database via SSH

### ISSUE THREAD

**Issue by markus138** [mzupan/nagios-plugin-mongodb#151]
Hello,
I like your plugin, but I've got a problem for connecting to my database since I normally connect to mongoDB via SSH. That means:

./check_mongodb.py -H 123.123.123.123 -u username -p password -A connections -W 60 -C 80

wont work. Is there a way to connect via ssh?

**Comment by mzupan** [comment]
no.. you need to either expose the mongo port to your nagios server or use something like nrpe to allow nagios to connect to and run the check locally

**Comment by markus138** [comment]
ok thanks
