### ISSUE TITLE
General MongoDB Error: can't set attribute

### ISSUE THREAD

**Issue by digitalcrab** [mzupan/nagios-plugin-mongodb#174]
Hello guys
I am trying to use this plugin to monitor replica lag by this command
```
check_mongodb.py -H mongo01 -A replication_lag -P 27017 -W 15 -C 30
```
But the result is 
```
CRITICAL - General MongoDB Error: can't set attribute
```

I am using nagios 3.5.1 pymongo 3.0.3 and master version of your plugin. MongoDb version 2.6.x and 3.0.3.
What I am doing wrong?

Thank you

**Comment by err0rs** [comment]
pip install pymongo==2.8

**Comment by fromYukki** [comment]
What about mongo 3.x?

**Comment by mpwhalen** [comment]
I am having the same problem. I tried changing from pymongo v. 3.0.1 back to v. 2.8 like you said, but now I am getting 
`'NoneType' object is unsubscriptable` 
Any ideas?

**Comment by err0rs** [comment]
Python 2.6.9 + pymongo 2.8 works for the following on mongod 3
        service_description  Mongo Connect Check
        service_description  Mongo Free Connections
        service_description  Mongo Replication Lag
        service_description  Mongo Replication Lag Percentage
        service_description  Mongo Memory Usage
        service_description  Mongo Mapped Memory Usage
        service_description  Mongo Flush Average
        service_description  Mongo Last Flush Time
        service_description  MongoDB state
        service_description  MongoDB Index Miss Ratio
        service_description  MongoDB Number of databases
        service_description  MongoDB Number of collections
        service_description  MongoDB Database size 
        service_description  MongoDB Database index size 
        service_description  Mongo Connect Check

**Comment by bbhenry** [comment]
Thanks for the tip, pymongo==2.8 also make things so much faster then pymongo==3.0.3. I was able to run a host list of checks under 2 seconds instead of 13.

**Comment by warrenpnz** [comment]
Actually the prom here is that readpreference in Pymongo 3 is now read only, e.g this:
````
 def set_read_preference(db):
     if pymongo.version >= "2.1":
        db.read_preference = pymongo.ReadPreference.SECONDARY
```
won't work as it is trying to set a read only attribute. It needs to be changed to:
```
 def set_read_preference(db):
    if pymongo.version >= "2.1":
        db.read_preference = pymongo.ReadPreference.SECONDARY
 else:
         pymongo.read_preferences.Secondary
```
That should fix it

**Comment by CorbMax** [comment]
I'm using MongoDB 3.0.7 and Python 2.6.6
I've fixed with pymongo 2.8 OR applying @warrenpnz note (both works).
Despite script runs fine (no errors), both fixes produce unreliable results:
```
> check_mongodb.py -H server -A database_size -P 27017 -W 300 -C 500 -d mydb
OK - Database size: 0 MB, Database: mydb
```
when `db.stats()` reports 64MB size for same database.

Also `connect` action reports unreliable results.
Checking real server:
```
> check_mongodb.py -H server -A connect -P 27017 -W 2 -C 4
OK - Connection took 0 seconds
```
Checking fake server (not exists - wrong port):
```
> check_mongodb.py -H fake_server -A connect -P 100 -W 2 -C 4
OK - Connection took 0 seconds
```

**Comment by k1-hedayati** [comment]
I have same issue, any plans on merging @yuchting's PR?
@mzupan

**Comment by mzupan** [comment]
I merged in the PR

**Comment by k1-hedayati** [comment]
+1

**Comment by k1-hedayati** [comment]
+1
