### ISSUE TITLE
CRITICAL - General MongoDB Error:

### ISSUE THREAD

**Issue by uncelvel** [mzupan/nagios-plugin-mongodb#175]
hi everybody
When i check mongo db in my server. It canot read a status Server also mongo is running on my Server
Input:mongo 10.58.56.13
Output:MongoDB shell version: 2.6.10
connecting to: 10.58.56.13/test
>
Input: /usr/local/nagios/libexec/check_mongodb.py -H 10.58.56.13 -A connect -P 27017 -W 2 -C 4
Output:OK - Connection took 0 seconds 
==> But any IP, any port when i fill in the input ways output :OK - Connection took 0 seconds 
(
 /usr/local/nagios/libexec/check_mongodb.py -H 10.58.56.13 -A connect -P 27017 -W 2 -C 4
=>OK - Connection took 0 seconds 
 /usr/local/nagios/libexec/check_mongodb.py -H 10.58.56.13 -A connect -P 270537 -W 2 -C 4
=>OK - Connection took 0 seconds 
 /usr/local/nagios/libexec/check_mongodb.py -H 10.58.56.52 -A connect -P 27017 -W 2 -C 4
=>OK - Connection took 0 seconds 
Stop mongo 
=>OK - Connection took 0 seconds 
)
Or
Input: /usr/local/nagios/libexec/check_mongodb.py -H 10.58.56.13 -A connections -P 27017 -W 70 -C 80
Output: CRITICAL - General MongoDB Error: command SON([('serverStatus', 1)]) on namespace admin.$cmd failed: not authorized on admin to execute command { serverStatus: 1 }
What can i do to fix this problem

**Comment by warrenpnz** [comment]
The user that you attach to the Mongo instance needs certain permissions:

MongoDB 2.4:
'roles' : [ 'readAnyDatabase', 'clusterAdmin' ],
'otherDBRoles' : { 'nagios' : [ 'readWrite' ] }

MongoDB 2.6+:
'roles' : [ 'readAnyDatabase', 'clusterMonitor' ],
'otherDBRoles' : { 'nagios' : [ 'readWrite' ] }

**Comment by uncelvel** [comment]
Thank for you help!
