### ISSUE TITLE
I need connect Mongo with SSL options, It's supported?

### ISSUE THREAD

**Issue by edodiazv** [mzupan/nagios-plugin-mongodb#207]
I need connect to mongodb on Cloud with SSL but not work, it's supported for the plugin?

An example is pymongo.MongoClient(MONGODB_URL,ssl_ca_certs="./servercert.crt")

Thanks in advance.

**Comment by mzupan** [comment]
#208 should fix it.

**Comment by edodiazv** [comment]
Thanks you!
