### ISSUE TITLE
Rounded connect time

### ISSUE THREAD

**Issue by tatref** [mzupan/nagios-plugin-mongodb#239]
Hi,

Is there a specific reason to round the connect time?
This appear in various places in the check, for example in main:
https://github.com/mzupan/nagios-plugin-mongodb/blob/f79ff703c0d483ad9685936f7463e325a122af59/check_mongodb.py#L209

An in check_connect:
https://github.com/mzupan/nagios-plugin-mongodb/blob/f79ff703c0d483ad9685936f7463e325a122af59/check_mongodb.py#L380-L383

Connect time is usually measured in ms, having a whole second seems weird:

    OK - Connection took 0 seconds

What do you think about displaying the time up to 3 digits (ms), and keeping the exact time for the perfdata? If I remove the round() in main, and change the check_connect function like so:

    message = "Connection took %.3f seconds" % conn_time 

The end result is:

    OK - Connection took 0.225 seconds | connection_time=0.224931001663;1.0;2.0

**Comment by mzupan** [comment]
Put in a PR and i'll accept it.
