### ISSUE TITLE
CRITICAL - General MongoDB Error: 'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists.

### ISSUE THREAD

**Issue by JustinBelterKTC** [mzupan/nagios-plugin-mongodb#265]
I am trying to run the command with the the following arguments
-H <ip_address>
-P 27017
-u <username>
-p <password>
-A collections
-D
--all-databases

I also have an issue where if I use just the -H,-P,-u,-p args I get "Username/Password incorrect" even though it works properly.

**Comment by JustinBelterKTC** [comment]
I figured the second issues out ("Username/Password incorrect"), the authenticate method is deprecated in pymongo, so instead I used 

client = MongoClient(username=user, password=passwd)

The authenicate method was removed in PyMongo v4.0, here is the changelog
https://pymongo.readthedocs.io/en/stable/changelog.html#breaking-changes-in-4-0

**Comment by RomyxBaps** [comment]
Hi,

I've got the same error with pymongo 4+.
Have you find a solution ?

**Comment by atwebm** [comment]
For my use-case, it worked to comment out the authenticate-Method and put the User and Password as parameter to the MongoClient-Method

`
    try:
        # ssl connection for pymongo > 2.3
        if pymongo.version >= "2.3":
            if replica is None:
                con = pymongo.MongoClient(host, port, username=user, password=passwd, **con_args)
            else:
                con = pymongo.MongoClient(host, port, username=user, password=passwd, read_preference=pymongo.ReadPreference.SECONDARY, replicaSet=replica, **con_args)
        else:
            if replica is None:
                con = pymongo.Connection(host, port, slave_okay=True, network_timeout=10)
            else:
                con = pymongo.Connection(host, port, slave_okay=True, network_timeout=10)

        # we must authenticate the connection, otherwise we won't be able to perform certain operations
#        if ssl_cert and ssl_ca_cert_file and user and auth_mechanism == 'SCRAM-SHA-256':
#            con.the_database.authenticate(user, mechanism='SCRAM-SHA-256')
#        elif ssl_cert and ssl_ca_cert_file and user and auth_mechanism == 'SCRAM-SHA-1':
#            con.the_database.authenticate(user, mechanism='SCRAM-SHA-1')
#        elif ssl_cert and ssl_ca_cert_file and user and auth_mechanism == 'MONGODB-X509':
#            con.the_database.authenticate(user, mechanism='MONGODB-X509')

        try:
          result = con.admin.command("ismaster")
        except ConnectionFailure:
          print("CRITICAL - Connection to Mongo server on %s:%s has failed" % (host, port) )
          sys.exit(2)

        if 'arbiterOnly' in result and result['arbiterOnly'] == True:
            print("OK - State: 7 (Arbiter on port %s)" % (port))
            sys.exit(0)

#        if user and passwd:
#            db = con[authdb]
#            try:
#              db.authenticate(user, password=passwd)
#            except PyMongoError:
#                sys.exit("Username/Password incorrect")

        # Ping to check that the server is responding.
        con.admin.command("ping")
`

**Comment by HOSTED-POWER** [comment]
Having the same problem, any official fix coming? :D

(We require pymongo 4.x for other purposes)

**Comment by MontyBeda** [comment]
To work with both new and old pymongo a to work with also Arbiter instances I had to do more changes and ended with this connection function:

def mongo_connect(host=None, port=None, ssl=False, user=None, passwd=None, replica=None, authdb="admin", insecure=False, ssl_ca_cert_file=None, ssl_cert=None, auth_mechanism=None, retry_writes_disabled=False):
    from pymongo.errors import ConnectionFailure
    from pymongo.errors import PyMongoError
    import ssl as SSL

    con_args = dict()

    if ssl:
        if insecure:
            con_args['ssl_cert_reqs'] = SSL.CERT_NONE
        else:
            con_args['ssl_cert_reqs'] = SSL.CERT_REQUIRED
        con_args['ssl'] = ssl
        if ssl_ca_cert_file:
            con_args['ssl_ca_certs'] = ssl_ca_cert_file
        if ssl_cert:
            con_args['ssl_certfile'] = ssl_cert

    if retry_writes_disabled:
        con_args['retryWrites'] = False

    try:
        # ssl connection for pymongo > 2.3
        if pymongo.version >= "2.3":
            if replica is None:
                con = pymongo.MongoClient(host, port, **con_args)
            else:
                con = pymongo.MongoClient(host, port, read_preference=pymongo.ReadPreference.SECONDARY, replicaSet=replica, **con_args)
        else:
            if replica is None:
                con = pymongo.Connection(host, port, slave_okay=True, network_timeout=10)
            else:
                con = pymongo.Connection(host, port, slave_okay=True, network_timeout=10)

        # we must authenticate the connection, otherwise we won't be able to perform certain operations
        if ssl_cert and ssl_ca_cert_file and user and auth_mechanism == 'SCRAM-SHA-256':
            con.the_database.authenticate(user, mechanism='SCRAM-SHA-256')
        elif ssl_cert and ssl_ca_cert_file and user and auth_mechanism == 'SCRAM-SHA-1':
            con.the_database.authenticate(user, mechanism='SCRAM-SHA-1')
        elif ssl_cert and ssl_ca_cert_file and user and auth_mechanism == 'MONGODB-X509':
            con.the_database.authenticate(user, mechanism='MONGODB-X509')

        try:
          result = con.admin.command("ismaster")
        except ConnectionFailure:
          print("CRITICAL - Connection to Mongo server on %s:%s has failed" % (host, port) )
          sys.exit(2)

        if 'arbiterOnly' in result and result['arbiterOnly'] == True:
            print("OK - State: 7 (Arbiter on port %s)" % (port))
            sys.exit(0)

        # Ping to check that the server is responding.
        con.admin.command("ping")

    except Exception as e:
        if isinstance(e, pymongo.errors.AutoReconnect) and str(e).find(" is an arbiter") != -1:
            # We got a pymongo AutoReconnect exception that tells us we connected to an Arbiter Server
            # This means: Arbiter is reachable and can answer requests/votes - this is all we need to know from an arbiter
            print("OK - State: 7 (Arbiter)")
            sys.exit(0)
        return exit_with_general_critical(e), None
    
    try:
        # ssl connection for pymongo > 2.3
        if pymongo.version >= "2.3":
            if replica is None:
                con = pymongo.MongoClient(host, port, username=user, password=passwd, **con_args)
            else:
                con = pymongo.MongoClient(host, port, username=user, password=passwd, read_preference=pymongo.ReadPreference.SECONDARY, replicaSet=replica, **con_args)
        else:
            if replica is None:
                con = pymongo.Connection(host, port, username=user, password=passwd, slave_okay=True, network_timeout=10)
            else:
                con = pymongo.Connection(host, port, username=user, password=passwd, slave_okay=True, network_timeout=10)

        # we must authenticate the connection, otherwise we won't be able to perform certain operations
        if ssl_cert and ssl_ca_cert_file and user and auth_mechanism == 'SCRAM-SHA-256':
            con.the_database.authenticate(user, mechanism='SCRAM-SHA-256')
        elif ssl_cert and ssl_ca_cert_file and user and auth_mechanism == 'SCRAM-SHA-1':
            con.the_database.authenticate(user, mechanism='SCRAM-SHA-1')
        elif ssl_cert and ssl_ca_cert_file and user and auth_mechanism == 'MONGODB-X509':
            con.the_database.authenticate(user, mechanism='MONGODB-X509')

        try:
          result = con.admin.command("ismaster")
        except ConnectionFailure:
          print("CRITICAL - Connection to Mongo server on %s:%s has failed" % (host, port) )
          sys.exit(2)

        # Ping to check that the server is responding.
        con.admin.command("ping")
    except Exception as e:
        return exit_with_general_critical(e), None
    return 0, con
