### ISSUE TITLE
General MongoDB Error: 'module' object has no attribute 'MongoClient'

### ISSUE THREAD

**Issue by eBeyond** [mzupan/nagios-plugin-mongodb#91]
When I'm running:
<code>/usr/lib/nagios/plugins/check_mongodb.py -H localhost -p 27017</code>
I receive the following error:
<code>CRITICAL - General MongoDB Error: 'module' object has no attribute 'MongoClient'</code>

pymongo is installed using the package python-pymongo (v:2.1-ubuntu0.1)

Do you have any idea?

**Comment by cgabhane** [comment]
Install the latest pymongo using (it worked for me)
python -m pip install pymongo==3.5.1
