### ISSUE TITLE
check_collections fail on slaves

### ISSUE THREAD

**Issue by gingerlime** [mzupan/nagios-plugin-mongodb#93]
Trying to run `check_mongodb.py -A collections -P 27017 -W 160 -C 200` will fail with:

`CRITICAL - General MongoDB Error: not master and slaveOk=false`. 

However, trying to pass `--replica <replicaname>` is prevented with a warning: 

`passing a replicaset while not checking replica_primary does not work`

If I comment-out the check:

```
    #elif not action == 'replica_primary' and replicaset:
    #    return "passing a replicaset while not checking replica_primary does not work"
```

Then it works fine. Happy to submit a pull request, to extend the test to other potential commands, but wanted to check first if there's something I'm perhaps missing?

**Comment by adrianlzt** [comment]
Fixed in #105
